### ISSUE TITLE
German Translation is False

### ISSUE THREAD

**Issue by Dryra** [jainishsenjaliya/js_contact_form#1]
Hello, 
I am using this plugin, and my website is in German, when implementing it I found that there are some spelling mistakes, like Adressen which should be Adresse, and Stad that should be Stadt.

Is it something that I can fix, is it typo3 wise or from the plugin ?

Thank you

**Comment by jainishsenjaliya** [comment]
You can set it form Plugin 

typo3conf/ext/js_contact_form/Resources/Private/Language/de.locallang.xlf

In new version i will update that both text
