### ISSUE TITLE
composer package name

### ISSUE THREAD

**Issue by AnatoliZich** [jainishsenjaliya/js_contact_form#2]
Hey,
the vendor name of your composer.json should not consist whitespaces. A valid package name would be "jainishsenjaliya/js-contact-form".

A satis repository even seems to break when a mirrored repository contains a package with wrong vendor names (which is the case for https://composer.typo3.org/packages.json).

It would be great if you could adjust your package name as mentioned above. That also is the case for your js_paginate extension.

Thanks!

**Comment by jainishsenjaliya** [comment]
Not getting you bro.

You mean i need to change in following file

https://github.com/jainishsenjaliya/js_contact_form/blob/master/composer.json

 "name": "Jainish Senjaliya/js_contact_form", to  "name": "jainishsenjaliya/js-contact-form" ???

can you please explain in jainishsenjaliya@gmail.com

**Comment by AnatoliZich** [comment]
you got it just right. Thats exactly what i meant.
Please adjust the composer.json of your js_paginate extension aswell.

**Comment by jainishsenjaliya** [comment]
Just uploaded new version.. 

Added new feature and modify composer file
